# Generated by Django 2.0.2 on 2020-08-07 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('Lifestyle', models.CharField(blank=True, max_length=100, null=True)),
                ('Sportevent', models.CharField(blank=True, max_length=100, null=True)),
                ('Travel', models.CharField(blank=True, max_length=100, null=True)),
                ('Entertainment_events', models.CharField(blank=True, max_length=100, null=True)),
                ('Hobbies', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
