# Generated by Django 2.0.2 on 2020-08-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='Cuisine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='Entertainment_events',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='Hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='Lifestyle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='Sportevent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='Travel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
